version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: market_king_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: market_king
      TZ: Asia/Tokyo
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    platform: linux/amd64

volumes:
  postgres_data:
