# Generated by Django 5.0.1 on 2025-02-25 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_time', models.DateTimeField()),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.yahooauctionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yahoo_auction',
            },
        ),
        migrations.CreateModel(
            name='YahooFreeMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_time', models.DateTimeField()),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.yahooauctionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yahoo_free_market',
            },
        ),
        migrations.CreateModel(
            name='Ebay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('offer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yahoo_auction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.yahooauction')),
                ('yahoo_free_market_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.yahoofreemarket')),
            ],
            options={
                'db_table': 'ebay',
            },
        ),
        migrations.DeleteModel(
            name='EbayRegisterFromYahooAuction',
        ),
        migrations.AddIndex(
            model_name='yahooauction',
            index=models.Index(fields=['status'], name='yahoo_aucti_status__62fff3_idx'),
        ),
        migrations.AddIndex(
            model_name='yahoofreemarket',
            index=models.Index(fields=['status'], name='yahoo_free__status__528e84_idx'),
        ),
        migrations.AddIndex(
            model_name='ebay',
            index=models.Index(fields=['sku'], name='ebay_sku_c3b181_idx'),
        ),
        migrations.AddIndex(
            model_name='ebay',
            index=models.Index(fields=['status'], name='ebay_status__59fb9f_idx'),
        ),
    ]
