# Generated by Django 5.0.1 on 2025-02-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_yahooauction_yahoofreemarket_ebay_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ebay',
            new_name='t_ebay_sku_a442ba_idx',
            old_name='ebay_sku_c3b181_idx',
        ),
        migrations.RenameIndex(
            model_name='ebay',
            new_name='t_ebay_status__0fecaf_idx',
            old_name='ebay_status__59fb9f_idx',
        ),
        migrations.RenameIndex(
            model_name='yahooauction',
            new_name='t_yahoo_auc_status__b71c32_idx',
            old_name='yahoo_aucti_status__62fff3_idx',
        ),
        migrations.RenameIndex(
            model_name='yahoofreemarket',
            new_name='t_yahoo_fre_status__0842a1_idx',
            old_name='yahoo_free__status__528e84_idx',
        ),
        migrations.AlterModelTable(
            name='ebay',
            table='t_ebay',
        ),
        migrations.AlterModelTable(
            name='yahooauction',
            table='t_yahoo_auction',
        ),
        migrations.AlterModelTable(
            name='yahoofreemarket',
            table='t_yahoo_free_market',
        ),
    ]
