# Generated by Django 5.0.1 on 2025-02-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_ebay_sku_c3b181_idx_t_ebay_sku_a442ba_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahoofreemarket',
            name='end_time',
        ),
    ]
