# Generated by Django 5.0.1 on 2025-04-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_yahoofreemarketstatus_alter_yahoofreemarket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
