# Generated by Django 5.0.1 on 2025-01-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shippingsurcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('yahoo_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yahoo_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('ebay_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ebay_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_setting',
            },
        ),
    ]
