# Generated by Django 5.0.1 on 2025-01-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_migrate_settings_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='yahoo_client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yahoo_client_secret',
        ),
    ]
