# Generated by Django 5.0.1 on 2025-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ebay_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebay',
            name='watch_count',
            field=models.IntegerField(default=0),
        ),
    ]
