# Generated by Django 5.0.1 on 2025-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_yahoo_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ebay_dev_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
