# Generated by Django 5.0.1 on 2025-04-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transactiontype_transaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactiontype',
            table='m_transaction_types',
        ),
    ]
