# Generated by Django 5.0.1 on 2025-01-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_setting_ebay_dev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ebay_user_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
