# Generated by Django 5.0.1 on 2025-04-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_transactiontype_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='updated_at',
        ),
    ]
