# Generated by Django 5.0.1 on 2025-01-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_ebay_user_token_setting_ebay_refresh_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='ebay_refresh_token',
            new_name='ebay_auth_token',
        ),
    ]
