# Generated by Django 5.0.1 on 2025-02-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_ebay_refresh_token_setting_ebay_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ebay_auth_token',
        ),
        migrations.AddField(
            model_name='setting',
            name='ebay_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
