# Generated by Django 5.0.1 on 2025-04-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_sku_transaction_management_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRatesDhl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_document', models.BooleanField(default=False)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'm_shipping_rates_dhl',
            },
        ),
        migrations.CreateModel(
            name='ShippingRatesEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'm_shipping_rates_economy',
            },
        ),
        migrations.CreateModel(
            name='ShippingRatesFedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'm_shipping_rates_fedex',
            },
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='service',
        ),
        migrations.RemoveField(
            model_name='shippingsurcharge',
            name='service',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='country_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='country_name_jp',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='service',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='zone',
        ),
        migrations.AddField(
            model_name='countries',
            name='zone_dhl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='zone_economy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='zone_fedex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='countries',
            index=models.Index(fields=['code'], name='m_countries_code_963222_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingratesdhl',
            index=models.Index(fields=['zone'], name='m_shipping__zone_6869e1_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingratesdhl',
            index=models.Index(fields=['weight'], name='m_shipping__weight_ee6d59_idx'),
        ),
        migrations.AddField(
            model_name='shippingrateseconomy',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
        migrations.AddIndex(
            model_name='shippingratesfedex',
            index=models.Index(fields=['zone'], name='m_shipping__zone_aad2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingratesfedex',
            index=models.Index(fields=['weight'], name='m_shipping__weight_4d6639_idx'),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.DeleteModel(
            name='ShippingSurcharge',
        ),
        migrations.AddIndex(
            model_name='shippingrateseconomy',
            index=models.Index(fields=['weight'], name='m_shipping__weight_78cf36_idx'),
        ),
    ]
