# Generated by Django 5.0.1 on 2025-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_shippingratesdhl_shippingrateseconomy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='zone_dhl',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='zone_economy',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='zone_fedex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shippingratesdhl',
            name='zone',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='shippingratesfedex',
            name='zone',
            field=models.CharField(max_length=2),
        ),
    ]
