# Generated by Django 5.0.1 on 2025-02-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_setting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ebay_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ebay_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
