# Generated by Django 5.0.1 on 2025-02-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_setting_ebay_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
