# Generated by Django 5.0.1 on 2025-04-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_countries_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
