# Generated by Django 5.0.1 on 2025-04-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_countries_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesDhl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250)),
                ('name_ja', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=2)),
                ('zone', models.CharField(max_length=2)),
                ('express_envelope', models.CharField(max_length=3)),
                ('express_worldwide', models.CharField(max_length=3)),
                ('express_worldwide_1200', models.CharField(max_length=3)),
                ('express_worldwide_1030', models.CharField(max_length=3)),
                ('express_worldwide_0900', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'm_countries_dhl',
                'indexes': [models.Index(fields=['code'], name='m_countries_code_b1e779_idx')],
            },
        ),
        migrations.CreateModel(
            name='CountriesEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250)),
                ('name_ja', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=2)),
                ('zone', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'm_countries_economy',
                'indexes': [models.Index(fields=['code'], name='m_countries_code_ec6f36_idx')],
            },
        ),
        migrations.AlterField(
            model_name='shippingrateseconomy',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countrieseconomy'),
        ),
        migrations.CreateModel(
            name='CountriesFedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250)),
                ('name_ja', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=2)),
                ('zone', models.CharField(max_length=2)),
                ('je_ip', models.CharField(max_length=3)),
                ('je_ficp', models.CharField(max_length=3)),
                ('ji_ip', models.CharField(max_length=3)),
                ('ji_ficp', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'm_countries_fedex',
                'indexes': [models.Index(fields=['code'], name='m_countries_code_37ab49_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
