# Generated by Django 5.0.1 on 2025-02-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_setting_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='deepl_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
