# Generated by Django 5.0.1 on 2025-04-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_countriesdhl_countrieseconomy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbaySKUHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_sku', models.CharField(max_length=255)),
                ('new_sku', models.CharField(max_length=255)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('ebay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_histories', to='api.ebay')),
            ],
            options={
                'db_table': 't_ebay_sku_history',
                'indexes': [models.Index(fields=['previous_sku'], name='t_ebay_sku__previou_a6b2cf_idx'), models.Index(fields=['new_sku'], name='t_ebay_sku__new_sku_6332e3_idx')],
            },
        ),
    ]
