# Generated by Django 5.0.1 on 2025-02-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_setting_deepl_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ebay_access_token',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ebay_refresh_token',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ebay_token_expires_at',
        ),
        migrations.CreateModel(
            name='EbayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(db_column='refresh_token')),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ebay_tokens',
            },
        ),
    ]
