# Generated by Django 5.0.1 on 2025-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ebayskuhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('product_name', models.TextField()),
                ('detail', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_expenses',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('product_name', models.TextField()),
                ('management_code', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('import_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('final_value_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('international_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('client_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('client_age', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_purchases',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('product_name', models.TextField()),
                ('management_code', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('client_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('client_age', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_sales',
            },
        ),
    ]
