# Generated by Django 5.0.1 on 2025-04-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_expense_purchase_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='insert_datetime',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='updated_at',
            new_name='update_datetime',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='created_at',
            new_name='insert_datetime',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='updated_at',
            new_name='update_datetime',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='created_at',
            new_name='insert_datetime',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='updated_at',
            new_name='update_datetime',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_by',
        ),
    ]
