# Generated by Django 5.0.1 on 2025-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_setting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayStoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(max_length=50, unique=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monthly_fee_annual', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('free_listings', models.IntegerField()),
                ('listing_fee_over_limit', models.CharField(max_length=100)),
                ('final_value_fee', models.CharField(max_length=100)),
                ('final_value_fee_category_discount', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_ebay_store_type',
            },
        ),
    ]
