# Generated by Django 5.0.1 on 2025-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ebaystoretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaystoretype',
            name='final_value_fee',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ebaystoretype',
            name='listing_fee_over_limit',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
