# Generated by Django 5.0.1 on 2025-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_ebay_final_profit_remove_ebay_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.TextField(null=True),
        ),
    ]
