# Generated by Django 5.0.1 on 2025-02-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_ebaystoretype_final_value_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ebay_store_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.ebaystoretype'),
            preserve_default=False,
        ),
    ]
