# Generated by Django 5.0.1 on 2025-04-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_purchase_product_name_alter_sale_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ebay_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ebay'),
        ),
        migrations.AddField(
            model_name='sale',
            name='ebay_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ebay'),
        ),
    ]
