# Generated by Django 5.0.1 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_setting_ebay_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystoretype',
            name='international_fee',
            field=models.DecimalField(decimal_places=1, default=1.35, max_digits=4),
            preserve_default=False,
        ),
    ]
