# Generated by Django 5.0.1 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ebaystoretype_international_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaystoretype',
            name='international_fee',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
