# Generated by Django 5.0.1 on 2025-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_ebaystoretype_international_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'm_tax',
            },
        ),
    ]
