# Generated by Django 5.0.1 on 2025-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_purchase_final_value_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
