# Generated by Django 5.0.1 on 2025-05-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_ebay_insert_user_ebay_update_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='ebay_store_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='api.ebaystoretype'),
        ),
    ]
