# Generated by Django 5.0.1 on 2025-02-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ebay_store_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='api.ebaystoretype'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service'),
        ),
        migrations.AlterField(
            model_name='shippingsurcharge',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service'),
        ),
        migrations.CreateModel(
            name='EbayRegisterFromYahooAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('ebay_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ebay_shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yahoo_auction_id', models.CharField(max_length=255)),
                ('yahoo_auction_item_name', models.CharField(max_length=255)),
                ('yahoo_auction_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yahoo_auction_shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yahoo_auction_end_time', models.DateTimeField()),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.status')),
            ],
            options={
                'db_table': 'ebay_register_from_yahoo_auction',
                'indexes': [models.Index(fields=['sku'], name='ebay_regist_sku_298b12_idx'), models.Index(fields=['status'], name='ebay_regist_status__ccc4c9_idx')],
            },
        ),
    ]
