# Generated by Django 5.0.1 on 2025-02-18 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_countries_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayregisterfromyahooauction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayregisterfromyahooauction',
            name='yahoo_auction_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
