# Generated by Django 5.0.1 on 2025-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_ebayregisterfromyahooauction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.IntegerField()),
                ('condition_enum', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'm_condition',
            },
        ),
    ]
