# Generated by Django 5.0.1 on 2025-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayregisterfromyahooauction',
            name='offer_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
